name: Release Rust Tool
description: Build and release a Rust tool
inputs:
  build_type:
    description: Build type
    required: true
    default: release
  target:
    description: Target triplet
    required: true
  executable_file_name:
    description: Executable name
    required: true
  executable_ext:
    description: Executable file name extension
    required: true
outputs:
  random_number:
    description: Random number
    value: ${{ steps.random_number_generator.outputs.random_number }}
runs:
  using: composite
  steps:
    - name: Set variables
      shell: bash
      run: |
        echo 'RUST_TOOL_ACTION_BUILD_VERSION=${{ github.ref_name }}-$(git rev-parse HEAD)' >> $GITHUB_ENV
        echo 'ARCHIVE_FILE_NAME=${{ inputs.executable_file_name }}-${{ github.ref_name }}-${{ inputs.target }}${{ matrix.archive_ext }}' >> $GITHUB_ENV
        echo 'CARGO_TERM_COLOR=always' >> $GITHUB_ENV
        echo 'CARGO=cargo' >> $GITHUB_ENV
        echo 'TARGET_ARGS=' >> $GITHUB_ENV
        echo 'OUTPUT_DIR=target' >> $GITHUB_ENV
        if [ '${{ inputs.build_type }}' == 'release' ]; then
          echo 'BUILD_TYPE_ARGS=--release' >> $GITHUB_ENV
        else
          echo 'BUILD_TYPE_ARGS=' >> $GITHUB_ENV
        fi

    - name: Install Cross
      shell: bash
      run: |
        #cargo install cross
        #echo "CARGO=cross" >> $GITHUB_ENV
        #echo "TARGET_ARGS=--target ${{ inputs.target }}" >> $GITHUB_ENV
        #echo "OUTPUT_DIR=target/${{ inputs.target }}" >> $GITHUB_ENV

    - name: Generate random number
      id: random_number_generator
      shell: bash
      run: \
        echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT

    - name: Set action path
      shell: bash
      run: |
        echo "github_action_path=${{ github.action_path }}"
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Probe
      shell: bash
      run: probe one two three

#      - name: Create archive
#        shell: bash
#        run: create-archive

#      - name: Generate checksum
#        shell: bash
#        run: |
#          ${{ matrix.sha256sum }} ${{ env.archive_file_name }} > ${{ env.archive_file_name }}.sha256sum

#      - name: Create release
#        id: create_release
#        uses: joutvhu/create-release@v1
#        with:
#          tag_name: ${{ github.ref_name }}
#          name: Release ${{ github.ref_name }}
#          body: ${{ env.project }} release ${{ github.ref_name }}
#          draft: false
#          prerelease: false
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload archive
#        uses: actions/upload-release-asset@v1.0.1
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ${{ env.archive_file_name }}
#          asset_name: ${{ env.archive_file_name }}
#          asset_content_type: application/octet-stream
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload checksum
#        uses: actions/upload-release-asset@v1.0.1
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ${{ env.archive_file_name }}.sha256sum
#          asset_name: ${{ env.archive_file_name }}.sha256sum
#          asset_content_type: text/plain
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
