name: Release Rust Tool
description: Build and release a Rust tool
inputs:
  tool_name:
    description: Tool name
    type: string
    required: true
  target:
    description: Target triplet
    type: string
    required: true
  executable_ext:
    description: Executable file name extension
    type: string
    required: true
  archive_type:
    description: Archive type
    type: string
    required: true
  build_type:
    description: Build type
    type: string
    required: true
    default: release
  code_sign:
    description: Sign executable (Windows only)
    type: boolean
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Code-sign executable
      if: ${{ inputs.code_sign == "true" }}
      shell: bash
      run: |
        echo CODE_SIGN_IS_TRUTHY

    - name: Code-sign executable
      if: ${{ inputs.code_sign != "true" }}
      shell: bash
      run: |
        echo CODE_SIGN_IS_FALSY
