#!/bin/bash
set -euo pipefail
output_dir=$1
build_type=$2
archive_file_name=$3
archive_ext=$4
executable_base_name=$5
executable_ext=$6
echo output_dir=$output_dir
echo build_type=$build_type
echo archive_file_name=$archive_file_name
echo archive_ext=$archive_ext
echo executable_base_name=$executable_base_name
echo executable_ext=$executable_ext

exit 0
if [ "$archive_ext" == '.tar.gz' ]; then
  tar \
    -C $output_dir/$build_type \
    -czf \
    $archive_file_name $executable_base_name$executable_ext
elif [ "$archive_ext" == '.zip' ]; then
  (cd $output_dir/$build_type && 7z \
    a \
    -tzip \
    $archive_file_name \
    $executable_base_name$executable_ext)
  mv $output_dir/$build_type/$archive_file_name .
else
  echo "Unsupported archive extension $archive_ext"
  exit 1
fi
